pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('pedido-service') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Security Scan') {
            steps {
                dir('pedido-service') {
                    sh 'trivy fs . || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('pedido-service') {
                    sh 'docker build -t pedido-service .'
                }
            }
        }

        stage('Image Scan') {
            steps {
                sh 'trivy image pedido-service || true'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop pedido-service || true
                    docker rm pedido-service || true
                    docker run -d --name pedido-service --network vinheria-net -p 3001:3001 pedido-service
                '''
            }
        }
    }
}
