pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t catalogo-service .'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop catalogo-service || true
                    docker rm catalogo-service || true
                    docker run -d --name catalogo-service -p 3002:3002 catalogo-service
                '''
            }
        }
    }
}
