pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'npm install'
                bat 'npm run build'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t catalogo-service .'
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                docker stop catalogo-service || echo nao rodando
                docker rm catalogo-service || echo nao existe
                docker run -d --name catalogo-service -p 3002:3002 catalogo-service
                '''
            }
        }
    }
}
''