pipeline {
    agent {
        docker { image 'node:20' }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('catalogo-service') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('catalogo-service') {
                    sh 'docker build -t catalogo-service .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker stop catalogo-service || echo "nao rodando"
                docker rm catalogo-service || echo "nao existe"
                docker run -d --name catalogo-service -p 3002:3002 catalogo-service
                '''
            }
        }
    }
}
